language: perl
perl:
  - "5.22"
  - "5.14"
  - "5.10"
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "ircs://irc.suikawiki.org:6697#mechanize"
    use_notice: true
env:
  global:
    secure: "PQD+P+nwwat8OR+fEnjE6BtXAhz6w4TZN8V1pwnNjROlGCZBv4mOo5N6t24sItrVYNZzDm6iwYypu8clhW6vqnQX6aAJiNiG8pUin9Qk/9JdYRDa8y7ZicxPpv9ViwklSuytyHSd8Wtpr1T3SIX+qmeXfQLrZgUNCnSzs8PJfNc="
after_success:
  - curl https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
