perl:
  - "5.14"
before_install: git submodule update --init
install: "make local-perl test-deps PERL_VERSION=5.14.2"
script: "make test"
notifications:
  email:
    - wakaba.5081@gmail.com
  irc:
    channels:
      - "suika.fam.cx#mechanize"
    use_notice: true
